# fly.toml

app = "fido-backend"

# If you are building your image using a Dockerfile in the root directory:
[build]
  dockerfile = "Dockerfile"

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"

# Set any environment variables your Spring Boot app may need:
[env]
  # SPRING_PROFILES_ACTIVE = "prod"

[[services]]
  # This port should match the server.port your Spring Boot app listens on
  internal_port = 8090
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    # Expose your app via HTTP on port 80
    handlers = ["http"]
    port = 80

  [[services.ports]]
    # Expose your app via HTTPS on port 443
    handlers = ["tls", "http"]
    port = 443

  # Health checks for your app can be configured here
  #[services.tcp_checks]
  #  grace_period = "5s"
  #  interval = "10s"
  #  timeout = "2s"
  #  threshold = 3
