apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app # Ensure this matches the labels in your Deployment/Pod
  ports:
    - protocol: TCP
      port: 7780 # The port the service will expose
      targetPort: 8090 # The port on the container where your app is listening

