apiVersion: v1
kind: Secret
metadata:
  name: db-cache-credentials
  labels:
    app: demo-app-credentials
type: Opaque
stringData:
  POSTGRES_URL: "" # replace with actual value
  POSTGRES_USERNAME: "" # replace with actual value
  POSTGRES_PASSWORD: "" # replace with actual value
  REDIS_URL: "" # replace with actual value
  REDIS_PASSWORD: "" # replace with actual value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-app
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-app
    spec:
      containers:
      - image: demo-app-v23:latest
        env:
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: db-cache-credentials
                key: POSTGRES_URL
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-cache-credentials
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-cache-credentials
                key: POSTGRES_PASSWORD
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: db-cache-credentials
                key: REDIS_URL
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-cache-credentials
                key: REDIS_PASSWORD
        ports:
          - containerPort: 8090
        name: demo-app-v23
        imagePullPolicy: Never
        resources: {}
status: {}
